### ISSUE TITLE
mathematical formulae displaying double slashes in place of single slashes

### ISSUE THREAD

**Issue by yash-nagar** [Wikidata/primarysources#131]
I extracted mathematical formulae from English wikipedia articles related to math (approximately 15,000). One example formula looks like the following:

\alpha_J = R_i - [R_f + \beta_{iM} \cdot (R_M - R_f)]

Then I used primary source tool to upload them on Wikidata. However, when I checked the same formula after uploading it on primary source tool, it looked like this:

\\alpha_J = R_i - [R_f + \\beta_{iM} \\cdot (R_M - R_f)]

All the single slashes were replaced by double slashes and due to this error, the formulas won't be approved. Is there any solution to this problem?

I have also attached the text file which contains all the formulas with their respective wikidata item number.
[formula_list.txt](https://github.com/Wikidata/primarysources/files/712245/formula_list.txt)

**Comment by thiemowmde** [comment]
* Are you talking about slashes or **back**slashes? Double backslashes are expected in certain situations. For example in JSON, double quotes must be escaped with a backslash, e.g. `"This is how to \"quote\" in JSON."`. And because backslashes do have this special meaning, they must be escaped too, resulting in double backslashes.
* I don't see "double slashes" anywhere, neither in your example above, nor in the attached text file, nor on Wikidata.
* What do you mean with you "checked"? Where and how? Do you see double backslashes while editing on Wikidata? That would be a bug. Do you see them in the JSON? That's expected.
* I'm afraid I don't understand what the attached text file represents. It appears none of these formulas is on Wikidata.

Do you want to populate the Wikidata database with these formulas? I had a quick look at the attached text file and kindly ask you to **not** do this. The formula your script extracted is almost always **wrong**. Example: https://en.wikipedia.org/wiki/Polarity_(international_relations) contains a single formula at the very end of the article, describing a very specific detail. This formula does **not** represent the subject of the article and should **not** be dumped into the Wikidata item without an actual human actually checking if this makes sense or not.

Please talk to the maintainers of the Wikidata game. Your data set may be a good source for a game (which includes exactly that required human interaction).

There are also things like `<ref>` in your text file.

**Comment by yash-nagar** [comment]
I mean a back slash here. I am not sure why only one slash is appearing here but I created the same issue a long time ago on phabricator:
https://phabricator.wikimedia.org/T148138#2859401
When I say "checked" it means that the claims are available to be approved or rejected when the primary source gadget is activated from user preference. But the problem is that all the single backslashes have been replaced by double back slashes. so even if you approve the claim, it won't because it is not in the correct format to display the formula.
Can you please tell me a bit more about the Wikidata game part.

**Comment by thiemowmde** [comment]
I'm not familiar with this code base, but I dug into this issue a bit.

First things first: The issue can very easily be reproduced by going to wikidata.org, enabling the Primary Sources tool and then going to an Item listed in the text file above, e.g. https://www.wikidata.org/wiki/Q3523867.

By looking at https://tools.wmflabs.org/wikidata-primary-sources/entities/Q3523867 I can see that the bogus double escaping is happening in the backend. Multiple places in the backend code base may cause this:
* The text file is parsed by https://github.com/Wikidata/primarysources/blob/master/backend/parser/Parser.cc#L83. I believe this code is correct. TSV text files should not (and this one is not) contain escaped characters, so no unescaping is necessary.
* The persistence layer is probably the root of this, either when `INSERT`ing the value at https://github.com/Wikidata/primarysources/blob/master/backend/persistence/Persistence.cc#L133, or when `SELECT`ing it at https://github.com/Wikidata/primarysources/blob/master/backend/persistence/Persistence.cc#L211. You should check if the database contains double quotes.

I still believe this dataset is bad for the primary sources tool because of the enormous error rate. It fits much better into the [Wikidata game](https://tools.wmflabs.org/wikidata-game/). There is already a game that follows the exact same idea for images: pick the first image from an article and propose it as a property.

**Comment by marfox** [comment]
> I still believe this dataset is bad for the primary sources tool because of the enormous error rate.

For this reason, I temporarily removed the dataset from the tool.

@yash-nagar, please do not open duplicate issues, see #127.
Also, please continue the discussion at https://phabricator.wikimedia.org/T148138.

**Comment by physikerwelt** [comment]
@thiemowmde I was reading your comments and I have some questions about the primary sources tool in general
> This formula does not represent the subject of the article and should not be dumped into the Wikidata item without an actual human actually checking if this makes sense or not.

I completely agree that the formula should not be dumped into Wikidata without human interaction. However, as I understand the data uploaded to the primary sources tool is always checked by a human and thus there it's not required to have about 100% precision. Is that correct?
I'm not an expert in `Polarity`, thus I cannot judge if the formula is relevant or not. However, I can see some rationality that this formula was chosen as a candidate.
* It's a displaystyle formula
* It has a definition list for the identifiers used in that formula
* Multiple language versions of that article contain that formula
* In one [particular language](https://id.wikipedia.org/wiki/Polaritas_(hubungan_internasional)) the paragraph describing the formula is about 30% of the overall page content

> I still believe this dataset is bad for the primary sources tool because of the enormous error rate.

This is interesting for research purposes. How did you calculate the error rate?

Is there are guide that helps to decide on the question game vs. primary sources for inserting data to wikidata? From my first impression after having checked the links it seems that in many cases one could use primary sources and a game at the same time. 

> There are also things like `<ref>` in your text file.

I expect that this problem was already solved by @yash-nagar since we talked about that several months ago. @yash-nagar  can you please upload the latest version of the dataset.


PS: There was an interesting discussion on using AI in Wikimedia projects at this year’s developer summit in SFO lead by @halfak .
I think this issue is a nice design pattern for the discussion on how much AI we want to employ.

**Comment by lydiapintscher** [comment]
> I completely agree that the formula should not be dumped into Wikidata without human interaction. However, as I understand the data uploaded to the primary sources tool is always checked by a human and thus there it's not required to have about 100% precision. Is that correct?

It is correct that the tool doesn't require 100% correctness. However we should strive for a higher rate than we have it there right now especially with obviously wrong things that can easily be fixed like the ref issue.

**Comment by yash-nagar** [comment]
@physikerwelt thank you very much for the elaborative description of the problem.

>However, as I understand the data uploaded to the primary sources tool is always checked by a human and thus there it's not required to have about 100% precision. Is that correct?

This is the exact reason why I wanted to use primary source tool to upload the data since I know my data is not 100 percent accurate and primary source tool requires human interaction before the data is approved or rejected.

>@yash-nagar can you please upload the latest version of the dataset.

I am trying to remove as many errors as possible from the data including the <ref> issue and much more. After I am done with this, I will upload the new dataset.
