### ISSUE TITLE
Add status indicators when the backend is slow

### ISSUE THREAD

**Issue by mineo** [Wikidata/primarysources#24]
Right now the call to the backends /any endpoint either times out or takes very long, but there's nothing indicating any activity. One of those spinning circle things would already be enough to at least show the request has been made (and maybe a red X or something to indicate it failed).

**Comment by wastl** [comment]
It seems better to improve the performance of the /any endpoint. :) I'll take a look tomorrow.

**Comment by wastl** [comment]
Hmm, in my tests the /any endpoint returns results in less than 5ms. Not sure where the problem comes from.

**Comment by mineo** [comment]
It's indeed working fine again. But I think most people have a few hops between their computer and tools.wmflabs.org that could fail/delay or drop their packets/whatever at any given point, so imho it's still a good idea to prepare for those cases.

**Comment by mineo** [comment]
https://tools.wmflabs.org/wikidata-primary-sources/entities/any?dataset= is again taking a few seconds to load or simply times out and https://tools.wmflabs.org/wikidata-primary-sources/status.html does not show any values.

**Comment by addshore** [comment]
Is there a way to tackle this speed issue? Rather than simply indicating to users when the tool is having an issue?

**Comment by wastl** [comment]
There is a way: move to a different infrastructure. The software itself is not the main issue here. As it is, we rely on the tools.wmflabs.org infrastructure with very limited resources and a slow database.

I was considering rewriting the backend using e.g. LevelDB, but the issue here is that this needs local file access, which is also not available on tools.wmflabs.org machines (well, they offer NFS, but that suffers from the same issues).

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148185

Moving forward, please drop your comments onto that Phabricator ticket.
