### ISSUE TITLE
Removes URL references that leads to 404

### ISSUE THREAD

**Issue by Tpt** [Wikidata/primarysources#48]
Asked here: https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool#Link_reference_URL.3F

**Comment by tomayac** [comment]
New (archived) talk reference: https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool/Archive/2015#Link_reference_URL.3F. 
Due to CORS restrictions, detecting ```404 Not Found``` errors can't be done on the front-end via XHR. Even with a temporary iframe the error condition is not exposed, see [this](http://stackoverflow.com/a/26641263) StackOverflow response.

Assigning @vrandezo (as a proxy?) since @Tpt currently is not part of the Google organization.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148182

Moving forward, please drop your comments onto that Phabricator ticket.
