### ISSUE TITLE
Random item always loads the same entity

### ISSUE THREAD

**Issue by marfox** [Wikidata/primarysources#57]
In the front-end, when you click on the `Random $DATASET item` link in the left menu, the returned entity is always the same.
This only happens for some datasets, namely `freebase-coordinates` and `strephit-soccer`.

**Comment by Tpt** [comment]
The root cause of this issue is that the random feature picks a random integer between 0 and the max of the ids of the statement in the dataset and then pick the first statement which id is greater than this integer.

So, with small datasets the picked statement is nearly always the first one.

I think this algorithm should be changed. But we have to find something that is fairly efficient (so "ORDER BY RAND() LIMIT 1" is not an option).

**Comment by wastl** [comment]
The problem is that there is no good algorithm that at the same time is reasonably fast and scalable (I took some time researching and thinking about it). 

The current algorithm won't provide a uniform random distribution in situations where there is a large ID space of already approved statements. In that case, the next unapproved statement after the large space is going to be much more likely than any other statement (so it's not always the first one).

I'd still say the random selection is "good enough" for bigger datasets, where the effect is not as dramatic.

**Comment by marfox** [comment]
This issue prevents users from working smoothly on smaller datasets, though.
If we want to standardize the flow for data donations and accept other datasets in the long term, I think we should fix it.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148180

Moving forward, please drop your comments onto that Phabricator ticket.
