### ISSUE TITLE
approve URL generates duplicate entry

### ISSUE THREAD

**Issue by Crazy1880** [Wikidata/primarysources#90]
Since today i got a problem to approve URL or other things. Yesterday, when I did, all works normal and goes to the existing entry. See normal:
![2016-04-04_richtig](https://cloud.githubusercontent.com/assets/14944867/14258435/c83cb840-faa2-11e5-9a96-fc5ab38bc276.JPG)

If I do in now, new entries will be generated again and again. See the wrong:

![2016-04-04_falsch](https://cloud.githubusercontent.com/assets/14944867/14258494/f5d51d88-faa2-11e5-9dee-3c41af0a8791.JPG)

@Tpt @wastl is there anything changed from yesterday to today???

**Comment by wastl** [comment]
I rolled out a new version of the backend yesterday, but it included only minor changes. Can you give me the entity ID so I can check?

**Comment by Crazy1880** [comment]
Moin Moin @wastl : https://www.wikidata.org/w/index.php?title=Q1017855&type=revision&diff=318722713&oldid=308470298

and this: https://www.wikidata.org/w/index.php?title=Q1017855&diff=next&oldid=318722713

In the other articles I stopped my working.

**Comment by Crazy1880** [comment]
@wastl Note: I checked it just now and noticed, its especially in date-fields.

**Comment by wastl** [comment]
Can you confirm that this is exclusively in date fields? I fixed a serialization bug in the TSV serialization with respect to the official syntax definition. The specification says that a date must have a preceding +0000000, which it didn't have before (only the +).

The backend sends this format to the frontend, which maybe expected the bug to be present and does not handle the 7 '0's properly @tomayac ?

**Comment by wastl** [comment]
Reference to the syntax definition: http://tools.wmflabs.org/wikidata-todo/quick_statements.php

**Comment by wastl** [comment]
Actually this looks like a Wikidata bug. If I analyse the JSON or XML returned by 

https://www.wikidata.org/w/api.php?action=wbgetentities&format=json&ids=Q1017855

the values are identical even on the data serialization level. Not sure what's going on, maybe @vrandezo can help?

**Comment by vrandezo** [comment]
in general, you can add the same statement several times - this is intentional. The "approve reference" function from the Primary Sources tool should not create the claim, i.e. this step

https://www.wikidata.org/w/index.php?title=Q1017855&type=revision&diff=318722713&oldid=308470298

should have been skipped. Not sure what has changed, I will ask the wikimedia-tech mailing list if they know what is going on.

**Comment by vrandezo** [comment]
I tried it myself here, it should be cleaned up afterwards too:

https://www.wikidata.org/wiki/Q92621

**Comment by wastl** [comment]
What has changed is the syntactic representation of the date. It is now conforming to the TSV specification at http://tools.wmflabs.org/wikidata-todo/quick_statements.php, where the year is of the form [+-]\d{11}, i.e. a sign followed by exactly 11 digits, possibly padded by 0. The parsers all properly deal with this value, but maybe somewhere there is a string-based comparison between e.g. +1947 and +00000001947.

**Comment by wastl** [comment]
The frontend just passes the claim as is to the Wikidata API, regardless whether it already exists or not

https://github.com/google/primarysources/blob/master/frontend/freebase2wikidata.js#L1537

I think what happens is that somewhere in the Wikidata API itself there is a string comparison not aware of the semantics of the time stamp and comparing a string with padded 0 to a string without them. Hard for me to find, though.

**Comment by Tpt** [comment]
Sorry for the slow reaction. I have the answer.

Wikibase have changed a year ago the timestamp serialization from a representation with a year on 11 digits for all cases to a year encoded in 4 digits (and more if it is needed). I propagated the change to Primary Sources backend because I believe that users usually want to manipulate the new version and it makes the conversion TSV -> Wikibase JSON quite easier. The code that detects in the frontend the duplicates is here: https://github.com/google/primarysources/blob/master/frontend/freebase2wikidata.js#L958

If you want to switch to the old TSV serialization you should change https://github.com/google/primarysources/blob/master/frontend/freebase2wikidata.js#L901 and https://github.com/google/primarysources/blob/master/frontend/freebase2wikidata.js#L1029
but I'm really in favour using in "our" TSV the new Wikibase timestamp serialization.

**Comment by tomayac** [comment]
Sorry, I am at a multi-day event this week, but am happy to quickly merge a pull request if anyone
creates it :-) Thanks, @Tpt for the investigations!

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148168

Moving forward, please drop your comments onto that Phabricator ticket.
