### ISSUE TITLE
approve or reject leaving entries behind

### ISSUE THREAD

**Issue by Crazy1880** [Wikidata/primarysources#94]
Moin Moin @Tpt @wastl ,
I don't really now, how to discribe the "failure". In the following article:
- https://www.wikidata.org/wiki/Q351055
- https://www.wikidata.org/wiki/Q367634
- https://www.wikidata.org/wiki/Q152453

I approved or rejected entries, but when I'm finished, there were still the entries I allready approved or rejected.

![2016-04-24_prt](https://cloud.githubusercontent.com/assets/14944867/14767341/5fa8fc2c-0a23-11e6-9151-7b9a35a701d2.JPG)

If you approve this entries, you'll get duplications. If you try to reject the entries, they'll become back and back and back again.

This behavior I have since yesterday evening. For more informations let me now. Note: I noticed it in this article, but I beleave there are more.

Regards

**Comment by wastl** [comment]
Could be related to a change in caching I rolled out, I'll check what goes wrong.

**Comment by wastl** [comment]
Weird, is this happening *right now*? I deployed another version this morning.

**Comment by wastl** [comment]
An explanation to what changed: previously, when updating a statement the entity would be completely removed from the cache and a subsequent request reloads it from the (updated) database. This is very inefficient, as the frontend issues a reload after every update. So yesterday's change instead of completely deleting the entry from the cache updates it insead (by removing the statement that was approved).

I tried this on my local setup and it worked. Wondering what is special in your case.

**Comment by Crazy1880** [comment]
Moin @wastl ,
yes, it is going on in this moments. I tried it in https://www.wikidata.org/wiki/Q192410#revision=324985665 with the same problem.

How could I help you?

**Comment by wastl** [comment]
Weird, because if I request the endpoint using curl it seems correct. Maybe the frontend sends the get request to fast?

**Comment by Crazy1880** [comment]
@wastl : Maybe. But you see in the screenshot, the entry is allready saved. So it seems that the code didn't notice, that the entry was allready saved. And what is really strange is that there is no rule where it appears.

**Comment by wastl** [comment]
I deployed a workaround, maybe it helps.

**Comment by Crazy1880** [comment]
Moin @wastl , I checked it for the three examples and could say, no, it doesn't work.

**Comment by wastl** [comment]
I'll try something else tonight, maybe it's a concurrency issue (different threads having different state)

**Comment by Crazy1880** [comment]
@wastl , Difference in the browser:

IE 11: 
![2016-04-25_ie](https://cloud.githubusercontent.com/assets/14944867/14792209/87024f70-0b19-11e6-8c8b-3b5812835d41.JPG)

Opera 36 (default browser): 
![2016-04-25_opera](https://cloud.githubusercontent.com/assets/14944867/14792229/a077e654-0b19-11e6-82a3-9df6ade5d78f.JPG)

Perhaps it would help. This screenshots I'd taken after I deleted cache, tmp and make a reload.

**Comment by wastl** [comment]
Does this happen only when clicking on "approve claim" or also for "approve reference"? For me it seems to work for "approve reference", but not for "approve claim". In the "claim" case, the frontend never sends a POST request to notify the backend that statements have been approved (only to the Wikidata API).

**Comment by wastl** [comment]
So my current theory is as follows:
1. this only happens on "approve claim" and never on "approve reference"
2. it also only happens when the claim is already present but you are still trying to approve it
3. in this case the UI should not even show "approve claim" because the claim is already present" - but for whatever reason the frontend does not realise

**Comment by wastl** [comment]
This might actually be related to #90

**Comment by Crazy1880** [comment]
@wastl 

1. for the "reject claim" too
2. in theory yes, but if I see it is still there, I try a reject.
3. ok

**Comment by marfox** [comment]
Probably due to this issue:
https://www.wikidata.org/wiki/Q21536207#revision=333165966
https://imgur.com/L2Kezva
The claim was approved, but it is still suggested.

@wastl, any thoughts on this?

**Comment by wastl** [comment]
@tomayac can you have a look? I think this is an issue in the UI, but I have trouble finding it.

**Comment by tomayac** [comment]
I checked both problems. It seems the writes from the front-end somehow do not make it to the back-end. I opened a random item [Q632229](https://www.wikidata.org/wiki/Q632229) and approved and rejected claims. The approval went through [just fine](https://www.wikidata.org/w/index.php?title=Q632229&type=revision&diff=341928371&oldid=316931253). 

(i) However, I could reproduce the duplicate claims being shown, the reason is that the uniqueness comparison does not take references into account, a known [@ToDo](https://github.com/google/primarysources/blob/master/frontend/freebase2wikidata.js#L805) up for grabs.

(ii) I could also in some cases reproduce the non-rejectable claims issue. I repeated disapproved statement [868483](https://tools.wmflabs.org/wikidata-primary-sources/statements/868483), but if you query the back-end for [incoming Freebase statements for Q632229](https://tools.wmflabs.org/wikidata-primary-sources/entities/Q632229), it keeps coming back as "unapproved" (search for "868483").

For (i), if someone wants to tackle this, happy to merge their Pull Request. For (ii), @wastl, do you have a suspicion why this could be the case?

**Comment by tomayac** [comment]
FWIW, [868483](https://tools.wmflabs.org/wikidata-primary-sources/statements/868483) still comes back as [unapproved](https://tools.wmflabs.org/wikidata-primary-sources/entities/Q632229), so not a caching issue at least.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148166

Moving forward, please drop your comments onto that Phabricator ticket.
